### ISSUE TITLE
Deploy.yml fails

### ISSUE THREAD

**Issue by sergiozygmunt** [LeoColomb/dispoflare#1]
**Describe the bug**
The provided `deploy.yml` fails to deploy because the name isn't defined - or the documentation isn't present telling the user how to configure the `deploy.yml`.

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. Click deploy to workers
2. The wizard doesn't run a deploy
3. Manually execute deploy.yml
4. Deploy fails
**Expected behavior**
The deploy.yml to not fail during builds

**Actual behavior**
Either a "project name not defined" build error or when that field is manually named a "this project does not exist" error

**Comment by LeoColomb** [comment]
Thanks a lot for opening this issue @sergiozygmunt!
I have to be honest, the project is still at its early days and might not be 100% functionnal and documented.

* Regarding the Worker deploy button, I'm a bit confused by Cloudflare documentation. The button is promoted for both Pages and Worker projects but seems to work only for Workers...
* For the deploy script, you need to configure few GitHub Actions secrests:
  * `CF_API_TOKEN` with your Cloudflare API token
  * `CF_ACCOUNT_ID` with your Cloudflare Account ID
  * `PROJECT_NAME` with a Cloudflare Pages project name

I jope this helps.

**Comment by sergiozygmunt** [comment]
Got it deployed - I created a blank Pages site named `dispoflare` and uploaded the demo file just to get it to deploy. Then, I set the secret to `dispoflare` and the deploy worked.
