### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by TheDextiN** [LeoColomb/dispoflare#517]
![image](https://github.com/user-attachments/assets/b5cccc51-6f6b-45c9-a691-f3495359906d)

please help me with it

**Comment by TheDextiN** [comment]
deployed successfully but getting this error:

![image](https://github.com/user-attachments/assets/90537800-bf95-478a-b007-30077fa2bc30)

**Comment by LeoColomb** [comment]
Hey @TheDextiN
Before providing any assistance, we need to clarify:
* Why have you sent me an email?
* What is your expectation with a "please help me with it" without providing a single piece of information?

**Comment by TheDextiN** [comment]
Aah sorry

I added this issue link for redirect here

**Comment by TheDextiN** [comment]
can you help me ?

**Comment by LeoColomb** [comment]
Thanks for your support.
I guess let's take the efficient way:
1. **Delete your current fork** (bottom of [settings page](https://github.com/TheDextiN/dispoflare/settings), delete)
2. **Follow the Cloudflare Deploy's** procedure via this link: [Deploy to Cloudflare Pages](https://deploy.workers.cloudflare.com/?url=https://github.com/LeoColomb/dispoflare&authed=true&apiTokenTmpl=%5B%7B%22key%22%3A%22page%22%2C%22type%22%3A%22edit%22%7D%2C%7B%22key%22%3A%22workers_kv_storage%22%2C%22type%22%3A%22edit%22%7D%2C%7B%22key%22%3A%22workers_scripts%22%2C%22type%22%3A%22edit%22%7D%2C%7B%22key%22%3A%22access%22%2C%22type%22%3A%22edit%22%7D%2C%7B%22key%22%3A%22email_routing_address%22%2C%22type%22%3A%22read%22%7D%2C%7B%22key%22%3A%22email_routing_rule%22%2C%22type%22%3A%22edit%22%7D%2C%7B%22key%22%3A%22zone%22%2C%22type%22%3A%22read%22%7D%2C%7B%22key%22%3A%22zone_settings%22%2C%22type%22%3A%22read%22%7D%5D&apiTokenName=Dispoflare)

**Comment by TheDextiN** [comment]
Can i get you contact where i can contact you directly

**Comment by LeoColomb** [comment]
Thanks for your reply, here is the most direct already.
Have you tried the steps mentioned previously?

**Comment by TheDextiN** [comment]
yes got this error:
![image](https://github.com/user-attachments/assets/5114958c-4908-4a79-bf08-fa1b5a9d603d)

**Comment by TheDextiN** [comment]
![Uploading image.png…]()
facing this while creating mail

**Comment by LeoColomb** [comment]
It should be fixed via https://github.com/LeoColomb/dispoflare/commit/624ce08fcde50b3a781de24d5f743ebc06fb05b6
Just go to your repository root page ang click on the Sync button.

**Comment by LeoColomb** [comment]
Closed via 624ce08fcde50b3a781de24d5f743ebc06fb05b6

**Comment by TheDextiN** [comment]
Ok working perfect

Can i make api of this which i want to use in telegram bot which will
directly create a email id

**Comment by LeoColomb** [comment]
You can use the POST action on the index, using the expected data:
https://github.com/LeoColomb/dispoflare/blob/624ce08fcde50b3a781de24d5f743ebc06fb05b6/app/routes/_index.tsx#L19-L23

Or, probably better, just use the Cloudflare API to do this directly:
https://developers.cloudflare.com/api/operations/email-routing-routing-rules-create-routing-rule

**Comment by TheDextiN** [comment]
No i mean like this

***@***.***

Using this worker will create mail id ***@***.***

**Comment by TheDextiN** [comment]
ok got it thank you so much for you support i was trying to make this API since last 1 month and finally with your guidance i made it successfully once again thank you so much.
