### ISSUE TITLE
Account ID or API Token are not valid

### ISSUE THREAD

**Issue by zeroresearch** [LeoColomb/dispoflare#67]
Following the exact instructions I run into the following error when trying to connect my cf account: Account ID or API Token are not valid. Check your Account ID is correct and API Token has permissions to Edit Workers

**Comment by LeoColomb** [comment]
Thanks for reporting @silentresearch.
That said, I'm not sure how this was possible.

Let's review the path:
1. You clicked on the Deploy with Workers button 
![image](https://github.com/LeoColomb/dispoflare/assets/846943/cd8cac8d-5c16-4201-8492-d21e933c1baa)
2. You have filled the form until the API Token filed, were you clicked on the link to generate one (in red in following screenshot) 
![image](https://github.com/LeoColomb/dispoflare/assets/846943/0af422b2-070e-4311-8a63-64049ce098f3)
3. You got a prefilled Cloudflare Token creation form, submitted it and got a token.
![image](https://github.com/LeoColomb/dispoflare/assets/846943/11a11f34-fdf2-4c79-828d-6c1c22dbd2be)
4. You finished the Deploy with Workers form and submitted it.

Are we aligned?

**Comment by silentresearch** [comment]
That is correct. I have tried with another cloudflare account too, to make sure it wasn't related to my account in particular.

-------- Original Message --------

**Comment by LeoColomb** [comment]
Could you post a screenshot of the error?

**Comment by silentresearch** [comment]
Sure

-------- Original Message --------

**Comment by silentresearch** [comment]
![Uploading Screenshot_20230814_134152_Chrome.jpg…]()

**Comment by LeoColomb** [comment]
@silentresearch Thanks, I'll investigate.

**Comment by LeoColomb** [comment]
Alright, the only way I managed to reproduced is when there is a mismatch between the account ID and the token.
Could you please try again:
* Make sure you copy the full account ID, trimmed of any space.
* Make sure the token is allowed to interact with that exact same account, by selecting it in the corresponding dropdown.
![image](https://github.com/LeoColomb/dispoflare/assets/846943/83b3c07c-bb30-4677-9380-52225a4151b7)
* Make sure you copy the full token (I know this seems dump, but, I mean…)

As this Deploy to Workers form is managed by Cloudflare themselves, the next step would be opening a ticket on their support portal.

**Comment by LeoColomb** [comment]
@silentresearch Did you manage to follow the mentioned steps?

**Comment by silentresearch** [comment]
Cloudflare fixed it. Something wasn't right with the account. But now all is fine.
